##
##  Mysql-Series ONLY writer
##
##  note the `backend = "BLACKHOLE"` below, this implys the Lines stop at the writer
##
##  Basically the same as cassandra blob writers
##


[statsd-proxy-map]
listen_server="statsd-proxy" # which listener to sit in front of  (must be in the main config)
default_backend="graphite-proxy"  # failing a match go here

    [statsd-proxy-map.accumulator]
#    backend = "BLACKHOLE"
    backend = "graphite-proxy"
    input_format = "statsd"
    output_format = "graphite"
    random_ticker_start = false


[graphite-proxy-map]
listen_server="graphite-proxy" # which listener to sit in front of  (must be in the main config)
default_backend="graphite-proxy"  # failing a match go here

    [graphite-proxy-map.accumulator]
    backend = "BLACKHOLE"
    input_format = "graphite"
    output_format = "graphite"
    random_ticker_start = false

    # aggregate bin counts
    accumulate_flush = "5s"
    times = ["1s:1h", "5s:5h", "1m:10h"]

    # cache objects to be shared (or not) across the writer backends
    [[graphite-proxy-map.accumulator.writer.caches]]
        name="gorilla"
        series_encoding="gorilla"
        bytes_per_metric=2048
        max_metrics=1024000  # for 1 million points @ 1024 b you'll need lots o ram
        # max_time_in_cache="2m" # force a cache flush for metrics in ram longer then this number
        # broadcast_length="128" # buffer channel for pushed overflow writes
        # overflow_method="drop" # if over bytes/maxmetrics for non-series writers, drop incoming
        # for non-series metrics, the typical behavior is to flush the highest counts first,
        # but that may mean lower counts never get written, this value "flips" the sorter at this % rate to
        # force the "smaller" ones to get written more often
        # low_fruit_rate= 0.25


    # mysql api, metrics writer and path indexer
    [graphite-proxy-map.accumulator.writer.metrics]
        name="my-metrics"
        driver = "mysql-triggered"
        dsn = "$ENV{MYSQL_USER:admin}:$ENV{MYSQL_PASS:}@tcp(localhost:3306)/cadent"
        cache = "gorilla"

    [graphite-proxy-map.accumulator.writer.indexer]
        name="my-indexer"
        driver = "mysql"
        dsn = "$ENV{MYSQL_USER:admin}:$ENV{MYSQL_PASS:}@tcp(localhost:3306)/cadent"

        [graphite-proxy-map.accumulator.writer.indexer.options]
            local_index_dir="/tmp/cadent_index"
            writes_per_second=200
            # assign things written to by this node as the "master" writer
            # if you have multiple writers you'll need to have UNIQUE ids for them
            writer_index=1

    [graphite-proxy-map.accumulator.api]
        base_path = "/graphite/"
        listen = "0.0.0.0:8083"
        # enable GZIP output compression:
        # for large request rates (100-200TPS), gzip can cause ALOT of GC, the default is OFF
        # if your volume is lowish you should enable this, probably should not enable if
        # you are using msgpack/protobufs as the format for returns
        enabled_gzip = false

        #  TLS the server if desired
        # key="/path/to/server.key"
        # cert="/path/to/server.crt"

        use_metrics="my-metrics"
        use_indexer="my-indexer"

    # Sub string type match
    [[graphite-proxy-map.map]]
        substring=".marvel"  # ignore elastic search marvel stuff
        reject=true