##
##  Cassandra-flat ONLY writer
##
##  note the `backend = "BLACKHOLE"` below, this implys the Lines stop at the writer
##
##  cadent --config=graphite-config.toml --prereg=graphite-cassandra-flat.toml
##
##

[statsd-proxy-map]
listen_server="statsd-proxy" # which listener to sit in front of  (must be in the main config)
default_backend="graphite-proxy"  # failing a match go here

    [statsd-proxy-map.accumulator]
    backend = "graphite-proxy"  # farm to relay
    input_format = "statsd"
    output_format = "graphite"
    accumulate_flush = "10s"
    options = [
            ["legacyNamespace", "true"],
            ["prefixGauge", "gauges"],
            ["prefixTimer", "timers"],
            ["prefixSets", "sets"],
            ["prefixCounter", ""],
            ["globalPrefix", "stats"],
            ["globalSuffix", ""],
            ["percentThreshold", "0.90,0.95,0.99"]
    ]


[graphite-proxy-map]
listen_server="graphite-proxy" # which listener to sit in front of  (must be in the main config)
default_backend="graphite-proxy"  # failing a match go here

    [graphite-proxy-map.accumulator]
    backend = "BLACKHOLE"  # DO not
    input_format = "graphite"
    output_format = "graphite"
    accumulate_flush = "5s"
    random_ticker_start = false

    # aggregate bin counts
    times = ["5s:1h", "1m:168h"]

        # cache objects to be shared (or not) across the writer backends
        [[graphite-proxy-map.accumulator.writer.caches]]
            name="protobuf"
            series_encoding="protobuf"
            bytes_per_metric=1024
            max_metrics=1024000  # for 1 million points @ 1024 b you'll need lots o ram
            # max_time_in_cache="2m" # force a cache flush for metrics in ram longer then this number
            # broadcast_length="128" # buffer channel for pushed overflow writes
            # overflow_method="drop" # if over bytes/maxmetrics for non-series writers, drop incoming
            # for non-series metrics, the typical behavior is to flush the highest counts first,
            # but that may mean lower counts never get written, this value "flips" the sorter at this % rate to
            # force the "smaller" ones to get written more often
            # low_fruit_rate= 0.25


    # AND write things to the cassandra DB
    # cassandra api, metrics writer and path indexer
    [graphite-proxy-map.accumulator.writer.metrics]
        name="cass-metrics"
        driver = "cassandra-flat"
        dsn = "127.0.0.1:9042"
        cache = "protobuf"
        [graphite-proxy-map.accumulator.writer.metrics.options]
        write_queue_length=100
        writes_per_second=500
        sniff=false



    [graphite-proxy-map.accumulator.writer.indexer]
        name="cass-indexer"
        driver = "cassandra"
        dsn = "127.0.0.1:9042"
        [graphite-proxy-map.accumulator.writer.indexer.options]
            # assign things written to by this node as the "master" writer
            writer_index=1
            local_index_dir="/tmp/cadent_index"
            writes_per_second=100
            sniff=false

    [graphite-proxy-map.accumulator.api]
        base_path = "/graphite/"
        listen = "0.0.0.0:8083"
        # this is the read cache that will keep the latest goods in ram
        read_cache_total_bytes=16384000
        read_cache_max_bytes_per_metric=16384
        use_metrics="cass-metrics"
        use_indexer="cass-indexer"


    # Sub string type match
    [[graphite-proxy-map.map]]
        substring=".marvel"  # ignore elastic search marvel stuff
        reject=true