##
##  Cassandra-flat ONLY writer
##
##  note the `backend = "BLACKHOLE"` below, this implys the Lines stop at the writer
##
##  cadent --config=graphite.toml --prereg=graphite-cassandra-flat.toml
##
##

[graphite-proxy-map]
listen_server="graphite-proxy" # which listener to sit in front of  (must be in the main config)
default_backend="graphite-proxy"  # failing a match go here

    [graphite-proxy-map.accumulator]
    backend = "BLACKHOLE"  # loop back, the code will bypass the accumulator on the second pass
    input_format = "graphite"
    output_format = "graphite"
    accumulate_flush = "5s"
    random_ticker_start = false

    # aggregate bin counts
    times = ["5s:1h", "1m:168h"]

    # cache objects to be shared (or not) across the writer backends
    [[graphite-proxy-map.accumulator.writer.caches]]
    name="gob"
    series_encoding="gob"
    bytes_per_metric=1024
    max_metrics=1024000  # for 1 million points @ 1024 b you'll need lots o ram
    low_fruit_rate= 0.25


    # AND write things to the cassandra DB
    # cassandra api, metrics writer and path indexer
    [graphite-proxy-map.accumulator.writer.metrics]
        name="my-metrics"
        driver = "mysql-flat"
        dsn = "$ENV{MYSQL_USER:admin}:$ENV{MYSQL_PASS:}@tcp(localhost:3306)/cadent"
        cache = "gob"

        [graphite-proxy-map.accumulator.writer.metrics.options]
        write_queue_length=100
        table = "metrics_flat"


    [graphite-proxy-map.accumulator.writer.indexer]
        name="my-indexer"
        driver = "mysql"
        dsn = "$ENV{MYSQL_USER:admin}:$ENV{MYSQL_PASS:}@tcp(localhost:3306)/cadent"
        [graphite-proxy-map.accumulator.writer.indexer.options]
        writes_per_second=100

    [graphite-proxy-map.accumulator.api]
        base_path = "/graphite/"
        listen = "0.0.0.0:8083"

        use_metrics="my-metrics"
        use_indexer="my-indexer"
